services:
  # Development service
  ai-server-dev:
    build:
      context: .
      target: dev  # Use the dev stage from Dockerfile
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - .:/app  # Mount local code for live reloading
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434

  # Testing service
  ai-server-test:
    build:
      context: .
      target: test  # Use the test stage from Dockerfile
    env_file: .env
    volumes:
      - .:/app  # Mount local code for running tests
    command: swift test 

  # Production service
  ai-server-prod:
    build:
      context: .
      target: prod  # Use the prod stage from Dockerfile
    env_file: .env
    ports:
      - "5000:5000"
    restart: unless-stopped

